# nombre = input('Cual es tu nombre: ')
# print('Tu nombre es', nombre)
# print(f'Tu nombre es {nombre}')
# numero = input('Escribe un numero: ')
numero = int(input('Escribe un numero: '))
print(type(numero))